apiVersion: cloudscaler.io/v1alpha1
kind: gcp
metadata:
  labels:
    app.kubernetes.io/name: cloudscaler
    app.kubernetes.io/managed-by: kustomize
  name: gcp-sample
spec:
  # TODO(user): Add fields here
