processor:
  ignoreGroupVersions:
    - "GVK"
    - "kubecloudscaler.cloud/v1alpha1"
    - "kubecloudscaler.cloud/v1alpha2"
  ignoreTypes:
    - "(K8s|Gcp|Flow)List$"
  ignoreFields:
    # - "status$"
    - "TypeMeta$"

render:
  kubernetesVersion: 1.33
